# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=8)),
                ('add1housenumberorname', models.CharField(max_length=30)),
                ('add1street1', models.CharField(max_length=30)),
                ('add1street2', models.CharField(max_length=30)),
                ('add1townorcity', models.CharField(max_length=30)),
                ('add1county', models.CharField(max_length=30)),
                ('add1country', models.CharField(max_length=30)),
                ('add1postcode', models.CharField(max_length=30)),
                ('add2housenumberorname', models.CharField(max_length=30)),
                ('add2street1', models.CharField(max_length=30)),
                ('add2street2', models.CharField(max_length=30)),
                ('add2townorcity', models.CharField(max_length=30)),
                ('add2county', models.CharField(max_length=30)),
                ('add2country', models.CharField(max_length=30)),
                ('add2postcode', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fbf_profile',
                'managed': True,
            },
        ),
    ]
