# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='add1country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add1county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add1housenumberorname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add1postcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add1street1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add1street2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add1townorcity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2housenumberorname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2postcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2street1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2street2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='add2townorcity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
