# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20170114_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(default='a', upload_to=b'documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 14, 13, 58, 13, 240296, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
