# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_auto_20170114_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, upload_to=b'documents/'),
        ),
    ]
