# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
    ]
