# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_remove_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to=b'documents/'),
        ),
    ]
