# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0009_auto_20170114_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to=meta.models.user_directory_path),
        ),
    ]
