# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_auto_20170116_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
