# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 21:28
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_profile_referral_code'),
    ]


