# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0015_auto_20170117_2128'),
    ]

    operations = [

        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
