# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-19 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_remove_profile_dob'),
    ]

